In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
heart_disease=pd.read_csv('/content/HeartDiseaseTrain-Test.csv')

In [3]:
heart_disease.head()

,age,sex,chest_pain_type,resting_blood_pressure,cholestoral,fasting_blood_sugar,rest_ecg,Max_heart_rate,exercise_induced_angina,oldpeak,slope,vessels_colored_by_flourosopy,thalassemia,target
0,52,Male,Typical angina,125,212,Lower than 120 mg/ml,ST-T wave abnormality,168,No,1.0,Downsloping,Two,Reversable Defect,0
1,53,Male,Typical angina,140,203,Greater than 120 mg/ml,Normal,155,Yes,3.1,Upsloping,Zero,Reversable Defect,0
2,70,Male,Typical angina,145,174,Lower than 120 mg/ml,ST-T wave abnormality,125,Yes,2.6,Upsloping,Zero,Reversable Defect,0
3,61,Male,Typical angina,148,203,Lower than 120 mg/ml,ST-T wave abnormality,161,No,0.0,Downsloping,One,Reversable Defect,0
4,62,Female,Typical angina,138,294,Greater than 120 mg/ml,ST-T wave abnormality,106,No,1.9,Flat,Three,Fixed Defect,0

In [4]:
heart_disease.shape

(1025, 14)

In [5]:
heart_disease.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   age                            1025 non-null   int64
 1   sex                            1025 non-null   object
 2   chest_pain_type                1025 non-null   object
 3   resting_blood_pressure         1025 non-null   int64
 4   cholestoral                    1025 non-null   int64
 5   fasting_blood_sugar            1025 non-null   object
 6   rest_ecg                       1025 non-null   object
 7   Max_heart_rate                 1025 non-null   int64
 8   exercise_induced_angina        1025 non-null   object
 9   oldpeak                        1025 non-null   float64
 10  slope                          1025 non-null   object
 11  vessels_colored_by_flourosopy  1025 non-null   object
 12  thalassemia                    1025 non-null   object
 13  target                         1025 non-null   int64
dtypes: float64(1), int64(5), object(8)
memory usage: 112.2+ KB

In [6]:
heart_disease['target'].value_counts()

target
1    526
0    499
Name: count, dtype: int64

apply lebel encoding

In [7]:
level_encoder=LabelEncoder()

In [8]:
heart_disease['sex']=level_encoder.fit_transform(heart_disease['sex'])
heart_disease['chest_pain_type']=level_encoder.fit_transform(heart_disease['chest_pain_type'])
heart_disease['fasting_blood_sugar']=level_encoder.fit_transform(heart_disease['fasting_blood_sugar'])
heart_disease['rest_ecg']=level_encoder.fit_transform(heart_disease['rest_ecg'])
heart_disease['exercise_induced_angina']=level_encoder.fit_transform(heart_disease['exercise_induced_angina'])
heart_disease['slope']=level_encoder.fit_transform(heart_disease['slope'])
heart_disease['vessels_colored_by_flourosopy']=level_encoder.fit_transform(heart_disease['vessels_colored_by_flourosopy'])
heart_disease['thalassemia']=level_encoder.fit_transform(heart_disease['thalassemia'])

In [9]:
heart_disease.head()

,age,sex,chest_pain_type,resting_blood_pressure,cholestoral,fasting_blood_sugar,rest_ecg,Max_heart_rate,exercise_induced_angina,oldpeak,slope,vessels_colored_by_flourosopy,thalassemia,target
0,52,1,3,125,212,1,2,168,0,1.0,0,3,3,0
1,53,1,3,140,203,0,1,155,1,3.1,2,4,3,0
2,70,1,3,145,174,1,2,125,1,2.6,2,4,3,0
3,61,1,3,148,203,1,2,161,0,0.0,0,1,3,0
4,62,0,3,138,294,0,2,106,0,1.9,1,2,0,0

apply data standardization

In [10]:
numeric_cols=[ 'age','resting_blood_pressure', 'cholestoral', 'Max_heart_rate','oldpeak']

In [11]:
standard_scaler=StandardScaler()

In [12]:
heart_disease[numeric_cols]=standard_scaler.fit_transform(heart_disease[numeric_cols])

In [13]:
heart_disease.head()

,age,sex,chest_pain_type,resting_blood_pressure,cholestoral,fasting_blood_sugar,rest_ecg,Max_heart_rate,exercise_induced_angina,oldpeak,slope,vessels_colored_by_flourosopy,thalassemia,target
0,-0.268437,1,3,-0.377636,-0.659332,1,2,0.821321,0,-0.060888,0,3,3,0
1,-0.158157,1,3,0.479107,-0.833861,0,1,0.255968,1,1.727137,2,4,3,0
2,1.716595,1,3,0.764688,-1.396233,1,2,-1.048692,1,1.301417,2,4,3,0
3,0.724079,1,3,0.936037,-0.833861,1,2,0.516900,0,-0.912329,0,1,3,0
4,0.834359,0,3,0.364875,0.930822,0,2,-1.874977,0,0.705408,1,2,0,0

In [14]:
heart_disease.tail()

,age,sex,chest_pain_type,resting_blood_pressure,cholestoral,fasting_blood_sugar,rest_ecg,Max_heart_rate,exercise_induced_angina,oldpeak,slope,vessels_colored_by_flourosopy,thalassemia,target
1020,0.503520,1,1,0.479107,-0.484803,1,2,0.647366,1,-0.912329,0,4,0,1
1021,0.613800,1,3,-0.377636,0.232705,1,1,-0.352873,1,1.471705,1,1,3,0
1022,-0.819834,1,3,-1.234378,0.562371,1,1,-1.353113,1,-0.060888,1,1,0,0
1023,-0.488996,0,3,-1.234378,0.155137,1,1,0.429923,0,-0.912329,0,4,0,1
1024,-0.047877,1,3,-0.663216,-1.124743,1,2,-1.570556,0,0.279688,1,1,3,0

split the data into train and test

In [15]:
x=heart_disease.drop(columns='target',axis=1)
y=heart_disease['target']

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y,random_state=2)

In [17]:
x_train.shape,x_test.shape,heart_disease.shape

((820, 13), (205, 13), (1025, 14))

train ml model

In [18]:
model=LogisticRegression()

In [19]:
model.fit(x_train,y_train)

LogisticRegression()

accuracy check

In [20]:
# accuracy check on train data
x_train_prediction=model.predict(x_train)
train_data_accuracy=accuracy_score(x_train_prediction,y_train)
print(train_data_accuracy)

0.8463414634146341

In [21]:
# accuracy check on test data
x_test_prediction=model.predict(x_test)
test_data_accuracy=accuracy_score(x_test_prediction,y_test)
print(test_data_accuracy)

0.8

making a predictive syatem

In [22]:
input_data=(0.503520,	1,	1,	0.479107,	-0.484803,	1,	2,	0.647366,	1,	-0.912329,	0,	4,	0 )
input_data_as_numpy_array=np.asarray(input_data)
input_data_reshaped=input_data_as_numpy_array.reshape(1,-1)
prediction=model.predict(input_data_reshaped)
print(prediction)
if(prediction[0]==0):
  print('patient has not heart_diseasse')
else:
  print('patient has heart_disease')

[1]
patient has heart_disease

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [23]:
import pickle

In [24]:
file_name='heart_disease_model.sav'
pickle.dump(model,open(file_name,'wb'))

In [26]:

import pandas as pd
import pickle
from sklearn.preprocessing import LabelEncoder
from google.colab import files

# 1. Upload original Heart Disease CSV file
uploaded = files.upload()
file_name = next(iter(uploaded))

heart_disease = pd.read_csv(file_name)

# 2. Categorical columns
categorical_columns = [
    'sex',
    'chest_pain_type',
    'fasting_blood_sugar',
    'rest_ecg',
    'exercise_induced_angina',
    'slope',
    'vessels_colored_by_flourosopy',
    'thalassemia'
]

# 3. Create a separate encoder for each column
heart_encoders = {}

for column in categorical_columns:
    encoder = LabelEncoder()
    encoder.fit(heart_disease[column].dropna())
    heart_encoders[column] = encoder

# 4. Save encoders
with open('heart_disease_encoders.sav', 'wb') as file:
    pickle.dump(heart_encoders, file)

# 5. Download the file
files.download('heart_disease_encoders.sav')

Saving HeartDiseaseTrain-Test.csv to HeartDiseaseTrain-Test (1).csv