In [1]:
# import dependencies
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder

data collection and preprocessing

In [2]:
mail_data=pd.read_csv('/content/mail_data.csv')

In [3]:
mail_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [4]:
mail_data['Category'].value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

spam--> spam mail  


ham --> not spam mail

In [5]:
mail_data.shape

(5572, 2)

In [6]:
mail_data.isnull().sum()

Category    0
Message     0
dtype: int64

In [7]:
x=mail_data['Message']
y=mail_data['Category']

In [8]:
print(x)
print(y)

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: object
0        ham
1        ham
2       spam
3        ham
4        ham
        ...
5567    spam
5568     ham
5569     ham
5570     ham
5571     ham
Name: Category, Length: 5572, dtype: object

In [9]:
x.shape

(5572,)

spliting data

In [10]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,stratify=y,random_state=3)

In [11]:
print(x.shape,x_train.shape,x_test.shape)

(5572,) (4457,) (1115,)

feature of text data(converting character data into numerical data and removing of unwanted symbols and grammar)

In [12]:
vectorizer=TfidfVectorizer(stop_words='english')  # it directly remove the stop words

In [13]:
x_train=vectorizer.fit_transform(x_train)
x_test=vectorizer.transform(x_test)

apply leval encoding for categorical data

In [14]:
Level_encoder=LabelEncoder()
y_train=Level_encoder.fit_transform(y_train)
y_test=Level_encoder.transform(y_test)

training model

In [15]:
model=LogisticRegression()

In [16]:
model.fit(x_train,y_train)

LogisticRegression()

accuracy check

In [17]:
# accuracy check on training data
x_train_prediction=model.predict(x_train)
accuracy=accuracy_score(x_train_prediction,y_train)
print(accuracy)

0.9679156383217411

In [18]:
# accuracy check on testing data
x_test_prediction=model.predict(x_test)
accuracy=accuracy_score(y_test,x_test_prediction)
print(accuracy)

0.9632286995515695

making predictive system

In [19]:
input=["SMS. ac Sptv: The New Jersey Devils and the Detroit Red Wings play Ice Hockey. Correct or Incorrect? End? Reply END SPTV"]

# convert text to feature vector
input_data_feature=vectorizer.transform(input)
# making prediction
prediction=model.predict(input_data_feature)
print(prediction[0])

if prediction[0]==0:
  print("ham mail")
else:
  print("spam mail")

0
ham mail

save trained model and trained vectorizer

In [20]:
import pickle

In [21]:
file_name="spam_mail_model.sav"
pickle.dump(model,open(file_name,'wb'))

In [22]:
file_name="spam_mail_vectorizer.sav"
pickle.dump(vectorizer,open(file_name,'wb'))